test download and extract ffmpeg in buildpack

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,7 +1,31 @@
 #!/usr/bin/env bash
 # bin/compile <build-dir> <cache-dir>
 
-echo "-----> Installing ffmpeg..."
-curl --silent --location http://johnvansickle.com/ffmpeg/builds/ffmpeg-git-64bit-static.tar.xz | tar xf
-ls
+# constants
+FFMPEG_DOWNLOAD_FILE=ffmpeg-git-64bit-static.tar.xz
+FFMPEG_DOWNLOAD_URL=http://johnvansickle.com/ffmpeg/builds/${FFMPEG_DOWNLOAD_FILE}
 
+# fail hard
+set -o pipefail
+# fail harder
+set -eu
+# move hidden files too, just in case
+shopt -s dotglob
+
+# define directories
+build_dir=$1
+cache_dir=$2/ffmpeg
+build_ffmpeg_dir=${build_dir}/ffmpeg
+
+echo "-----> Installing ffmpeg..."
+if ls ${cache_dir}/${FFMPEG_DOWNLOAD_FILE} &>/dev/null
+then
+    echo "Using cached ffmpeg at ${cache_dir}/${FFMPEG_DOWNLOAD_FILE}..."
+else
+    echo "Downloading ffmpeg..."
+    curl –silent –output ${cache_dir}/${FFMPEG_DOWNLOAD_FILE} $FFMPEG_DOWNLOAD_URL
+fi
+
+mkdir ${build_ffmpeg_dir}
+tar xf ${cache_dir}/${FFMPEG_DOWNLOAD_FILE} /ffmpeg-git-20160608-64bit-static/ -c ${build_ffmpeg_dir}
+ls -laH ${build_ffmpeg_dir}
